from libcst import *

from flow_of_control import FlowOfControl, FoCBranchNode
from utils import code_gen


class TestGenerator:
    def __init__(self, foc: FlowOfControl):
        self.foc = foc

    def _generate_functions(self):
        functions = []

        nodes = [self.foc.root]

        while nodes:
            cur_node = nodes.pop(0)
            nodes = cur_node.children + nodes

            if len(cur_node.children) == 0:
                assert isinstance(cur_node, FoCBranchNode), f'is {type(cur_node)}'

                print('!!!!', code_gen(cur_node.condition))

        return [
            FunctionDef(
                name=Name(
                    value='test_something',
                ),
                params=Parameters(
                    params=[
                        Param(
                            name=Name(
                                value='self',
                                lpar=[],
                                rpar=[],
                            ),
                            annotation=None,
                            equal=MaybeSentinel.DEFAULT,
                            default=None,
                            comma=MaybeSentinel.DEFAULT,
                            star='',
                            whitespace_after_star=SimpleWhitespace(
                                value='',
                            ),
                            whitespace_after_param=SimpleWhitespace(
                                value='',
                            ),
                        ),
                    ],
                    star_arg=MaybeSentinel.DEFAULT,
                    kwonly_params=[],
                    star_kwarg=None,
                    posonly_params=[],
                    posonly_ind=MaybeSentinel.DEFAULT,
                ),
                body=IndentedBlock(
                    body=[
                        SimpleStatementLine(
                            body=[
                                Assign(
                                    targets=[
                                        AssignTarget(
                                            target=Name(
                                                value='in_out_list',
                                                lpar=[],
                                                rpar=[],
                                            ),
                                            whitespace_before_equal=SimpleWhitespace(
                                                value=' ',
                                            ),
                                            whitespace_after_equal=SimpleWhitespace(
                                                value=' ',
                                            ),
                                        ),
                                    ],
                                    value=List(
                                        elements=[],
                                        lbracket=LeftSquareBracket(
                                            whitespace_after=ParenthesizedWhitespace(
                                                first_line=TrailingWhitespace(
                                                    whitespace=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                    comment=None,
                                                    newline=Newline(
                                                        value=None,
                                                    ),
                                                ),
                                                empty_lines=[
                                                    EmptyLine(
                                                        indent=True,
                                                        whitespace=SimpleWhitespace(
                                                            value='    ',
                                                        ),
                                                        comment=Comment(
                                                            value='# TODO: Fill with input output pairs in form of "((args, kwargs), return_val)"',
                                                        ),
                                                        newline=Newline(
                                                            value=None,
                                                        ),
                                                    ),
                                                    EmptyLine(
                                                        indent=True,
                                                        whitespace=SimpleWhitespace(
                                                            value='    ',
                                                        ),
                                                        comment=Comment(
                                                            value='# TODO: These values should cover all edge cases and stuff...',
                                                        ),
                                                        newline=Newline(
                                                            value=None,
                                                        ),
                                                    ),
                                                ],
                                                indent=True,
                                                last_line=SimpleWhitespace(
                                                    value='',
                                                ),
                                            ),
                                        ),
                                        rbracket=RightSquareBracket(
                                            whitespace_before=SimpleWhitespace(
                                                value='',
                                            ),
                                        ),
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    semicolon=MaybeSentinel.DEFAULT,
                                ),
                            ],
                            leading_lines=[],
                            trailing_whitespace=TrailingWhitespace(
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                        ),
                        For(
                            target=Tuple(
                                elements=[
                                    Element(
                                        value=Tuple(
                                            elements=[
                                                Element(
                                                    value=Name(
                                                        value='args',
                                                        lpar=[],
                                                        rpar=[],
                                                    ),
                                                    comma=Comma(
                                                        whitespace_before=SimpleWhitespace(
                                                            value='',
                                                        ),
                                                        whitespace_after=SimpleWhitespace(
                                                            value=' ',
                                                        ),
                                                    ),
                                                ),
                                                Element(
                                                    value=Name(
                                                        value='kwargs',
                                                        lpar=[],
                                                        rpar=[],
                                                    ),
                                                    comma=MaybeSentinel.DEFAULT,
                                                ),
                                            ],
                                            lpar=[
                                                LeftParen(
                                                    whitespace_after=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                ),
                                            ],
                                            rpar=[
                                                RightParen(
                                                    whitespace_before=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                ),
                                            ],
                                        ),
                                        comma=Comma(
                                            whitespace_before=SimpleWhitespace(
                                                value='',
                                            ),
                                            whitespace_after=SimpleWhitespace(
                                                value=' ',
                                            ),
                                        ),
                                    ),
                                    Element(
                                        value=Name(
                                            value='return_val',
                                            lpar=[],
                                            rpar=[],
                                        ),
                                        comma=MaybeSentinel.DEFAULT,
                                    ),
                                ],
                                lpar=[],
                                rpar=[],
                            ),
                            iter=Name(
                                value='in_out_list',
                                lpar=[],
                                rpar=[],
                            ),
                            body=IndentedBlock(
                                body=[
                                    SimpleStatementLine(
                                        body=[
                                            Assign(
                                                targets=[
                                                    AssignTarget(
                                                        target=Name(
                                                            value='real_return_val',
                                                            lpar=[],
                                                            rpar=[],
                                                        ),
                                                        whitespace_before_equal=SimpleWhitespace(
                                                            value=' ',
                                                        ),
                                                        whitespace_after_equal=SimpleWhitespace(
                                                            value=' ',
                                                        ),
                                                    ),
                                                ],
                                                value=Call(
                                                    func=Name(
                                                        value='something',
                                                        lpar=[],
                                                        rpar=[],
                                                    ),
                                                    args=[
                                                        Arg(
                                                            value=Name(
                                                                value='args',
                                                                lpar=[],
                                                                rpar=[],
                                                            ),
                                                            keyword=None,
                                                            equal=MaybeSentinel.DEFAULT,
                                                            comma=Comma(
                                                                whitespace_before=SimpleWhitespace(
                                                                    value='',
                                                                ),
                                                                whitespace_after=SimpleWhitespace(
                                                                    value=' ',
                                                                ),
                                                            ),
                                                            star='*',
                                                            whitespace_after_star=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                            whitespace_after_arg=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                        ),
                                                        Arg(
                                                            value=Name(
                                                                value='kwargs',
                                                                lpar=[],
                                                                rpar=[],
                                                            ),
                                                            keyword=None,
                                                            equal=MaybeSentinel.DEFAULT,
                                                            comma=MaybeSentinel.DEFAULT,
                                                            star='**',
                                                            whitespace_after_star=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                            whitespace_after_arg=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                        ),
                                                    ],
                                                    lpar=[],
                                                    rpar=[],
                                                    whitespace_after_func=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                    whitespace_before_args=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                ),
                                                semicolon=MaybeSentinel.DEFAULT,
                                            ),
                                        ],
                                        leading_lines=[],
                                        trailing_whitespace=TrailingWhitespace(
                                            whitespace=SimpleWhitespace(
                                                value='',
                                            ),
                                            comment=None,
                                            newline=Newline(
                                                value=None,
                                            ),
                                        ),
                                    ),
                                    SimpleStatementLine(
                                        body=[
                                            Expr(
                                                value=Call(
                                                    func=Attribute(
                                                        value=Name(
                                                            value='self',
                                                            lpar=[],
                                                            rpar=[],
                                                        ),
                                                        attr=Name(
                                                            value='assertEqual',
                                                            lpar=[],
                                                            rpar=[],
                                                        ),
                                                        dot=Dot(
                                                            whitespace_before=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                            whitespace_after=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                        ),
                                                        lpar=[],
                                                        rpar=[],
                                                    ),
                                                    args=[
                                                        Arg(
                                                            value=Name(
                                                                value='return_val',
                                                                lpar=[],
                                                                rpar=[],
                                                            ),
                                                            keyword=None,
                                                            equal=MaybeSentinel.DEFAULT,
                                                            comma=Comma(
                                                                whitespace_before=SimpleWhitespace(
                                                                    value='',
                                                                ),
                                                                whitespace_after=SimpleWhitespace(
                                                                    value=' ',
                                                                ),
                                                            ),
                                                            star='',
                                                            whitespace_after_star=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                            whitespace_after_arg=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                        ),
                                                        Arg(
                                                            value=Name(
                                                                value='real_return_val',
                                                                lpar=[],
                                                                rpar=[],
                                                            ),
                                                            keyword=None,
                                                            equal=MaybeSentinel.DEFAULT,
                                                            comma=MaybeSentinel.DEFAULT,
                                                            star='',
                                                            whitespace_after_star=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                            whitespace_after_arg=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                        ),
                                                    ],
                                                    lpar=[],
                                                    rpar=[],
                                                    whitespace_after_func=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                    whitespace_before_args=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                ),
                                                semicolon=MaybeSentinel.DEFAULT,
                                            ),
                                        ],
                                        leading_lines=[],
                                        trailing_whitespace=TrailingWhitespace(
                                            whitespace=SimpleWhitespace(
                                                value='',
                                            ),
                                            comment=None,
                                            newline=Newline(
                                                value=None,
                                            ),
                                        ),
                                    ),
                                ],
                                header=TrailingWhitespace(
                                    whitespace=SimpleWhitespace(
                                        value='',
                                    ),
                                    comment=None,
                                    newline=Newline(
                                        value=None,
                                    ),
                                ),
                                indent=None,
                                footer=[],
                            ),
                            orelse=None,
                            asynchronous=None,
                            leading_lines=[
                                EmptyLine(
                                    indent=False,
                                    whitespace=SimpleWhitespace(
                                        value='',
                                    ),
                                    comment=None,
                                    newline=Newline(
                                        value=None,
                                    ),
                                ),
                            ],
                            whitespace_after_for=SimpleWhitespace(
                                value=' ',
                            ),
                            whitespace_before_in=SimpleWhitespace(
                                value=' ',
                            ),
                            whitespace_after_in=SimpleWhitespace(
                                value=' ',
                            ),
                            whitespace_before_colon=SimpleWhitespace(
                                value='',
                            ),
                        ),
                    ],
                    header=TrailingWhitespace(
                        whitespace=SimpleWhitespace(
                            value='',
                        ),
                        comment=None,
                        newline=Newline(
                            value=None,
                        ),
                    ),
                    indent=None,
                    footer=[],
                ),
                decorators=[],
                returns=None,
                asynchronous=None,
                leading_lines=[],
                lines_after_decorators=[],
                whitespace_after_def=SimpleWhitespace(
                    value=' ',
                ),
                whitespace_after_name=SimpleWhitespace(
                    value='',
                ),
                whitespace_before_params=SimpleWhitespace(
                    value='',
                ),
                whitespace_before_colon=SimpleWhitespace(
                    value='',
                ),
            ), ]

    def _generate_module(self) -> Module:
        test_functions = self._generate_functions()

        return Module(
            body=[
                SimpleStatementLine(
                    body=[
                        Import(
                            names=[
                                ImportAlias(
                                    name=Name(
                                        value='unittest',
                                    ),
                                ),
                            ],
                        ),
                    ],
                ),
                ClassDef(
                    name=Name(
                        value='MyTestCase',
                    ),
                    body=IndentedBlock(
                        body=test_functions,
                    ),
                    bases=[
                        Arg(
                            value=Attribute(
                                value=Name(
                                    value='unittest',
                                ),
                                attr=Name(
                                    value='TestCase',
                                ),
                            ),
                        ),
                    ],
                ),
                If(
                    test=Comparison(
                        left=Name(
                            value='__name__',
                        ),
                        comparisons=[
                            ComparisonTarget(
                                operator=Equal(),
                                comparator=SimpleString(
                                    value="'__main__'",
                                ),
                            ),
                        ],
                    ),
                    body=IndentedBlock(
                        body=[
                            SimpleStatementLine(
                                body=[
                                    Expr(
                                        value=Call(
                                            func=Attribute(
                                                value=Name(
                                                    value='unittest',
                                                ),
                                                attr=Name(
                                                    value='main',
                                                ),
                                            ),
                                        ),
                                    ),
                                ],
                            ),
                        ],
                    ),
                ),
            ],
        )

    def generate(self) -> str:
        test_module = self._generate_module()

        return test_module.code
