Module(
    body=[
        SimpleStatementLine(
            body=[
                ImportFrom(
                    module=Name(
                        value='time',
                        lpar=[],
                        rpar=[],
                    ),
                    names=[
                        ImportAlias(
                            name=Name(
                                value='sleep',
                                lpar=[],
                                rpar=[],
                            ),
                            asname=AsName(
                                name=Name(
                                    value='sleep2',
                                    lpar=[],
                                    rpar=[],
                                ),
                                whitespace_before_as=SimpleWhitespace(
                                    value=' ',
                                ),
                                whitespace_after_as=SimpleWhitespace(
                                    value=' ',
                                ),
                            ),
                            comma=MaybeSentinel.DEFAULT,
                        ),
                    ],
                    relative=[],
                    lpar=None,
                    rpar=None,
                    semicolon=MaybeSentinel.DEFAULT,
                    whitespace_after_from=SimpleWhitespace(
                        value=' ',
                    ),
                    whitespace_before_import=SimpleWhitespace(
                        value=' ',
                    ),
                    whitespace_after_import=SimpleWhitespace(
                        value=' ',
                    ),
                ),
            ],
            leading_lines=[],
            trailing_whitespace=TrailingWhitespace(
                whitespace=SimpleWhitespace(
                    value='',
                ),
                comment=None,
                newline=Newline(
                    value=None,
                ),
            ),
        ),
        FunctionDef(
            name=Name(
                value='function_to_be_tested',
                lpar=[],
                rpar=[],
            ),
            params=Parameters(
                params=[
                    Param(
                        name=Name(
                            value='i',
                            lpar=[],
                            rpar=[],
                        ),
                        annotation=None,
                        equal=MaybeSentinel.DEFAULT,
                        default=None,
                        comma=MaybeSentinel.DEFAULT,
                        star='',
                        whitespace_after_star=SimpleWhitespace(
                            value='',
                        ),
                        whitespace_after_param=SimpleWhitespace(
                            value='',
                        ),
                    ),
                ],
                star_arg=MaybeSentinel.DEFAULT,
                kwonly_params=[],
                star_kwarg=None,
                posonly_params=[],
                posonly_ind=MaybeSentinel.DEFAULT,
            ),
            body=IndentedBlock(
                body=[
                    SimpleStatementLine(
                        body=[
                            Expr(
                                value=Call(
                                    func=Name(
                                        value='print',
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    args=[
                                        Arg(
                                            value=SimpleString(
                                                value="'i is:'",
                                                lpar=[],
                                                rpar=[],
                                            ),
                                            keyword=None,
                                            equal=MaybeSentinel.DEFAULT,
                                            comma=Comma(
                                                whitespace_before=SimpleWhitespace(
                                                    value='',
                                                ),
                                                whitespace_after=SimpleWhitespace(
                                                    value=' ',
                                                ),
                                            ),
                                            star='',
                                            whitespace_after_star=SimpleWhitespace(
                                                value='',
                                            ),
                                            whitespace_after_arg=SimpleWhitespace(
                                                value='',
                                            ),
                                        ),
                                        Arg(
                                            value=Name(
                                                value='i',
                                                lpar=[],
                                                rpar=[],
                                            ),
                                            keyword=None,
                                            equal=MaybeSentinel.DEFAULT,
                                            comma=MaybeSentinel.DEFAULT,
                                            star='',
                                            whitespace_after_star=SimpleWhitespace(
                                                value='',
                                            ),
                                            whitespace_after_arg=SimpleWhitespace(
                                                value='',
                                            ),
                                        ),
                                    ],
                                    lpar=[],
                                    rpar=[],
                                    whitespace_after_func=SimpleWhitespace(
                                        value='',
                                    ),
                                    whitespace_before_args=SimpleWhitespace(
                                        value='',
                                    ),
                                ),
                                semicolon=MaybeSentinel.DEFAULT,
                            ),
                        ],
                        leading_lines=[],
                        trailing_whitespace=TrailingWhitespace(
                            whitespace=SimpleWhitespace(
                                value='',
                            ),
                            comment=None,
                            newline=Newline(
                                value=None,
                            ),
                        ),
                    ),
                    If(
                        test=Comparison(
                            left=Name(
                                value='i',
                                lpar=[],
                                rpar=[],
                            ),
                            comparisons=[
                                ComparisonTarget(
                                    operator=LessThanEqual(
                                        whitespace_before=SimpleWhitespace(
                                            value=' ',
                                        ),
                                        whitespace_after=SimpleWhitespace(
                                            value=' ',
                                        ),
                                    ),
                                    comparator=Integer(
                                        value='0',
                                        lpar=[],
                                        rpar=[],
                                    ),
                                ),
                            ],
                            lpar=[],
                            rpar=[],
                        ),
                        body=IndentedBlock(
                            body=[
                                SimpleStatementLine(
                                    body=[
                                        Return(
                                            value=Integer(
                                                value='0',
                                                lpar=[],
                                                rpar=[],
                                            ),
                                            whitespace_after_return=SimpleWhitespace(
                                                value=' ',
                                            ),
                                            semicolon=MaybeSentinel.DEFAULT,
                                        ),
                                    ],
                                    leading_lines=[],
                                    trailing_whitespace=TrailingWhitespace(
                                        whitespace=SimpleWhitespace(
                                            value='',
                                        ),
                                        comment=None,
                                        newline=Newline(
                                            value=None,
                                        ),
                                    ),
                                ),
                            ],
                            header=TrailingWhitespace(
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                            indent=None,
                            footer=[],
                        ),
                        orelse=None,
                        leading_lines=[
                            EmptyLine(
                                indent=False,
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                        ],
                        whitespace_before_test=SimpleWhitespace(
                            value=' ',
                        ),
                        whitespace_after_test=SimpleWhitespace(
                            value='',
                        ),
                    ),
                    If(
                        test=Call(
                            func=Name(
                                value='isinstance',
                                lpar=[],
                                rpar=[],
                            ),
                            args=[
                                Arg(
                                    value=BinaryOperation(
                                        left=Name(
                                            value='i',
                                            lpar=[],
                                            rpar=[],
                                        ),
                                        operator=Add(
                                            whitespace_before=SimpleWhitespace(
                                                value=' ',
                                            ),
                                            whitespace_after=SimpleWhitespace(
                                                value=' ',
                                            ),
                                        ),
                                        right=Integer(
                                            value='9',
                                            lpar=[],
                                            rpar=[],
                                        ),
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    keyword=None,
                                    equal=MaybeSentinel.DEFAULT,
                                    comma=Comma(
                                        whitespace_before=SimpleWhitespace(
                                            value='',
                                        ),
                                        whitespace_after=SimpleWhitespace(
                                            value=' ',
                                        ),
                                    ),
                                    star='',
                                    whitespace_after_star=SimpleWhitespace(
                                        value='',
                                    ),
                                    whitespace_after_arg=SimpleWhitespace(
                                        value='',
                                    ),
                                ),
                                Arg(
                                    value=Name(
                                        value='int',
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    keyword=None,
                                    equal=MaybeSentinel.DEFAULT,
                                    comma=MaybeSentinel.DEFAULT,
                                    star='',
                                    whitespace_after_star=SimpleWhitespace(
                                        value='',
                                    ),
                                    whitespace_after_arg=SimpleWhitespace(
                                        value='',
                                    ),
                                ),
                            ],
                            lpar=[],
                            rpar=[],
                            whitespace_after_func=SimpleWhitespace(
                                value='',
                            ),
                            whitespace_before_args=SimpleWhitespace(
                                value='',
                            ),
                        ),
                        body=IndentedBlock(
                            body=[
                                SimpleStatementLine(
                                    body=[
                                        Expr(
                                            value=Call(
                                                func=Name(
                                                    value='print',
                                                    lpar=[],
                                                    rpar=[],
                                                ),
                                                args=[
                                                    Arg(
                                                        value=SimpleString(
                                                            value="'Yooo'",
                                                            lpar=[],
                                                            rpar=[],
                                                        ),
                                                        keyword=None,
                                                        equal=MaybeSentinel.DEFAULT,
                                                        comma=MaybeSentinel.DEFAULT,
                                                        star='',
                                                        whitespace_after_star=SimpleWhitespace(
                                                            value='',
                                                        ),
                                                        whitespace_after_arg=SimpleWhitespace(
                                                            value='',
                                                        ),
                                                    ),
                                                ],
                                                lpar=[],
                                                rpar=[],
                                                whitespace_after_func=SimpleWhitespace(
                                                    value='',
                                                ),
                                                whitespace_before_args=SimpleWhitespace(
                                                    value='',
                                                ),
                                            ),
                                            semicolon=MaybeSentinel.DEFAULT,
                                        ),
                                    ],
                                    leading_lines=[],
                                    trailing_whitespace=TrailingWhitespace(
                                        whitespace=SimpleWhitespace(
                                            value='',
                                        ),
                                        comment=None,
                                        newline=Newline(
                                            value=None,
                                        ),
                                    ),
                                ),
                            ],
                            header=TrailingWhitespace(
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                            indent=None,
                            footer=[],
                        ),
                        orelse=If(
                            test=Comparison(
                                left=Name(
                                    value='i',
                                    lpar=[],
                                    rpar=[],
                                ),
                                comparisons=[
                                    ComparisonTarget(
                                        operator=Is(
                                            whitespace_before=SimpleWhitespace(
                                                value=' ',
                                            ),
                                            whitespace_after=SimpleWhitespace(
                                                value=' ',
                                            ),
                                        ),
                                        comparator=Name(
                                            value='None',
                                            lpar=[],
                                            rpar=[],
                                        ),
                                    ),
                                ],
                                lpar=[],
                                rpar=[],
                            ),
                            body=IndentedBlock(
                                body=[
                                    SimpleStatementLine(
                                        body=[
                                            Expr(
                                                value=Call(
                                                    func=Name(
                                                        value='print',
                                                        lpar=[],
                                                        rpar=[],
                                                    ),
                                                    args=[
                                                        Arg(
                                                            value=Name(
                                                                value='None',
                                                                lpar=[],
                                                                rpar=[],
                                                            ),
                                                            keyword=None,
                                                            equal=MaybeSentinel.DEFAULT,
                                                            comma=MaybeSentinel.DEFAULT,
                                                            star='',
                                                            whitespace_after_star=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                            whitespace_after_arg=SimpleWhitespace(
                                                                value='',
                                                            ),
                                                        ),
                                                    ],
                                                    lpar=[],
                                                    rpar=[],
                                                    whitespace_after_func=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                    whitespace_before_args=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                ),
                                                semicolon=MaybeSentinel.DEFAULT,
                                            ),
                                        ],
                                        leading_lines=[],
                                        trailing_whitespace=TrailingWhitespace(
                                            whitespace=SimpleWhitespace(
                                                value='',
                                            ),
                                            comment=None,
                                            newline=Newline(
                                                value=None,
                                            ),
                                        ),
                                    ),
                                ],
                                header=TrailingWhitespace(
                                    whitespace=SimpleWhitespace(
                                        value='',
                                    ),
                                    comment=None,
                                    newline=Newline(
                                        value=None,
                                    ),
                                ),
                                indent=None,
                                footer=[],
                            ),
                            orelse=Else(
                                body=IndentedBlock(
                                    body=[
                                        SimpleStatementLine(
                                            body=[
                                                Expr(
                                                    value=Call(
                                                        func=Name(
                                                            value='print',
                                                            lpar=[],
                                                            rpar=[],
                                                        ),
                                                        args=[
                                                            Arg(
                                                                value=SimpleString(
                                                                    value="'Meh'",
                                                                    lpar=[],
                                                                    rpar=[],
                                                                ),
                                                                keyword=None,
                                                                equal=MaybeSentinel.DEFAULT,
                                                                comma=MaybeSentinel.DEFAULT,
                                                                star='',
                                                                whitespace_after_star=SimpleWhitespace(
                                                                    value='',
                                                                ),
                                                                whitespace_after_arg=SimpleWhitespace(
                                                                    value='',
                                                                ),
                                                            ),
                                                        ],
                                                        lpar=[],
                                                        rpar=[],
                                                        whitespace_after_func=SimpleWhitespace(
                                                            value='',
                                                        ),
                                                        whitespace_before_args=SimpleWhitespace(
                                                            value='',
                                                        ),
                                                    ),
                                                    semicolon=MaybeSentinel.DEFAULT,
                                                ),
                                            ],
                                            leading_lines=[],
                                            trailing_whitespace=TrailingWhitespace(
                                                whitespace=SimpleWhitespace(
                                                    value='',
                                                ),
                                                comment=None,
                                                newline=Newline(
                                                    value=None,
                                                ),
                                            ),
                                        ),
                                    ],
                                    header=TrailingWhitespace(
                                        whitespace=SimpleWhitespace(
                                            value='',
                                        ),
                                        comment=None,
                                        newline=Newline(
                                            value=None,
                                        ),
                                    ),
                                    indent=None,
                                    footer=[],
                                ),
                                leading_lines=[],
                                whitespace_before_colon=SimpleWhitespace(
                                    value='',
                                ),
                            ),
                            leading_lines=[],
                            whitespace_before_test=SimpleWhitespace(
                                value=' ',
                            ),
                            whitespace_after_test=SimpleWhitespace(
                                value='',
                            ),
                        ),
                        leading_lines=[
                            EmptyLine(
                                indent=False,
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                        ],
                        whitespace_before_test=SimpleWhitespace(
                            value=' ',
                        ),
                        whitespace_after_test=SimpleWhitespace(
                            value='',
                        ),
                    ),
                    If(
                        test=Comparison(
                            left=Name(
                                value='i',
                                lpar=[],
                                rpar=[],
                            ),
                            comparisons=[
                                ComparisonTarget(
                                    operator=GreaterThan(
                                        whitespace_before=SimpleWhitespace(
                                            value=' ',
                                        ),
                                        whitespace_after=SimpleWhitespace(
                                            value=' ',
                                        ),
                                    ),
                                    comparator=Integer(
                                        value='9',
                                        lpar=[],
                                        rpar=[],
                                    ),
                                ),
                            ],
                            lpar=[],
                            rpar=[],
                        ),
                        body=IndentedBlock(
                            body=[
                                If(
                                    test=Comparison(
                                        left=Name(
                                            value='i',
                                            lpar=[],
                                            rpar=[],
                                        ),
                                        comparisons=[
                                            ComparisonTarget(
                                                operator=LessThan(
                                                    whitespace_before=SimpleWhitespace(
                                                        value=' ',
                                                    ),
                                                    whitespace_after=SimpleWhitespace(
                                                        value=' ',
                                                    ),
                                                ),
                                                comparator=Integer(
                                                    value='10',
                                                    lpar=[],
                                                    rpar=[],
                                                ),
                                            ),
                                        ],
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    body=IndentedBlock(
                                        body=[
                                            SimpleStatementLine(
                                                body=[
                                                    AugAssign(
                                                        target=Name(
                                                            value='i',
                                                            lpar=[],
                                                            rpar=[],
                                                        ),
                                                        operator=SubtractAssign(
                                                            whitespace_before=SimpleWhitespace(
                                                                value=' ',
                                                            ),
                                                            whitespace_after=SimpleWhitespace(
                                                                value=' ',
                                                            ),
                                                        ),
                                                        value=Integer(
                                                            value='1',
                                                            lpar=[],
                                                            rpar=[],
                                                        ),
                                                        semicolon=MaybeSentinel.DEFAULT,
                                                    ),
                                                ],
                                                leading_lines=[],
                                                trailing_whitespace=TrailingWhitespace(
                                                    whitespace=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                    comment=None,
                                                    newline=Newline(
                                                        value=None,
                                                    ),
                                                ),
                                            ),
                                        ],
                                        header=TrailingWhitespace(
                                            whitespace=SimpleWhitespace(
                                                value='',
                                            ),
                                            comment=None,
                                            newline=Newline(
                                                value=None,
                                            ),
                                        ),
                                        indent=None,
                                        footer=[],
                                    ),
                                    orelse=None,
                                    leading_lines=[],
                                    whitespace_before_test=SimpleWhitespace(
                                        value=' ',
                                    ),
                                    whitespace_after_test=SimpleWhitespace(
                                        value='',
                                    ),
                                ),
                                If(
                                    test=Comparison(
                                        left=Name(
                                            value='i',
                                            lpar=[],
                                            rpar=[],
                                        ),
                                        comparisons=[
                                            ComparisonTarget(
                                                operator=Equal(
                                                    whitespace_before=SimpleWhitespace(
                                                        value=' ',
                                                    ),
                                                    whitespace_after=SimpleWhitespace(
                                                        value=' ',
                                                    ),
                                                ),
                                                comparator=Integer(
                                                    value='9',
                                                    lpar=[],
                                                    rpar=[],
                                                ),
                                            ),
                                        ],
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    body=IndentedBlock(
                                        body=[
                                            SimpleStatementLine(
                                                body=[
                                                    Assert(
                                                        test=Name(
                                                            value='False',
                                                            lpar=[],
                                                            rpar=[],
                                                        ),
                                                        msg=None,
                                                        comma=MaybeSentinel.DEFAULT,
                                                        whitespace_after_assert=SimpleWhitespace(
                                                            value=' ',
                                                        ),
                                                        semicolon=MaybeSentinel.DEFAULT,
                                                    ),
                                                ],
                                                leading_lines=[],
                                                trailing_whitespace=TrailingWhitespace(
                                                    whitespace=SimpleWhitespace(
                                                        value='',
                                                    ),
                                                    comment=None,
                                                    newline=Newline(
                                                        value=None,
                                                    ),
                                                ),
                                            ),
                                        ],
                                        header=TrailingWhitespace(
                                            whitespace=SimpleWhitespace(
                                                value='',
                                            ),
                                            comment=None,
                                            newline=Newline(
                                                value=None,
                                            ),
                                        ),
                                        indent=None,
                                        footer=[],
                                    ),
                                    orelse=None,
                                    leading_lines=[],
                                    whitespace_before_test=SimpleWhitespace(
                                        value=' ',
                                    ),
                                    whitespace_after_test=SimpleWhitespace(
                                        value='',
                                    ),
                                ),
                            ],
                            header=TrailingWhitespace(
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                            indent=None,
                            footer=[],
                        ),
                        orelse=None,
                        leading_lines=[
                            EmptyLine(
                                indent=False,
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                        ],
                        whitespace_before_test=SimpleWhitespace(
                            value=' ',
                        ),
                        whitespace_after_test=SimpleWhitespace(
                            value='',
                        ),
                    ),
                    SimpleStatementLine(
                        body=[
                            Expr(
                                value=Call(
                                    func=Name(
                                        value='sleep2',
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    args=[
                                        Arg(
                                            value=Integer(
                                                value='4',
                                                lpar=[],
                                                rpar=[],
                                            ),
                                            keyword=None,
                                            equal=MaybeSentinel.DEFAULT,
                                            comma=MaybeSentinel.DEFAULT,
                                            star='',
                                            whitespace_after_star=SimpleWhitespace(
                                                value='',
                                            ),
                                            whitespace_after_arg=SimpleWhitespace(
                                                value='',
                                            ),
                                        ),
                                    ],
                                    lpar=[],
                                    rpar=[],
                                    whitespace_after_func=SimpleWhitespace(
                                        value='',
                                    ),
                                    whitespace_before_args=SimpleWhitespace(
                                        value='',
                                    ),
                                ),
                                semicolon=MaybeSentinel.DEFAULT,
                            ),
                        ],
                        leading_lines=[
                            EmptyLine(
                                indent=False,
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                        ],
                        trailing_whitespace=TrailingWhitespace(
                            whitespace=SimpleWhitespace(
                                value='',
                            ),
                            comment=None,
                            newline=Newline(
                                value=None,
                            ),
                        ),
                    ),
                    SimpleStatementLine(
                        body=[
                            Return(
                                value=SimpleString(
                                    value='"Yay! I\'m going to be tested using this project!"',
                                    lpar=[],
                                    rpar=[],
                                ),
                                whitespace_after_return=SimpleWhitespace(
                                    value=' ',
                                ),
                                semicolon=MaybeSentinel.DEFAULT,
                            ),
                        ],
                        leading_lines=[],
                        trailing_whitespace=TrailingWhitespace(
                            whitespace=SimpleWhitespace(
                                value='',
                            ),
                            comment=None,
                            newline=Newline(
                                value=None,
                            ),
                        ),
                    ),
                ],
                header=TrailingWhitespace(
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
                indent=None,
                footer=[],
            ),
            decorators=[],
            returns=None,
            asynchronous=None,
            leading_lines=[
                EmptyLine(
                    indent=True,
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
                EmptyLine(
                    indent=True,
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
            ],
            lines_after_decorators=[],
            whitespace_after_def=SimpleWhitespace(
                value=' ',
            ),
            whitespace_after_name=SimpleWhitespace(
                value='',
            ),
            whitespace_before_params=SimpleWhitespace(
                value='',
            ),
            whitespace_before_colon=SimpleWhitespace(
                value='',
            ),
        ),
        FunctionDef(
            name=Name(
                value='another_function',
                lpar=[],
                rpar=[],
            ),
            params=Parameters(
                params=[],
                star_arg=MaybeSentinel.DEFAULT,
                kwonly_params=[],
                star_kwarg=None,
                posonly_params=[],
                posonly_ind=MaybeSentinel.DEFAULT,
            ),
            body=IndentedBlock(
                body=[
                    SimpleStatementLine(
                        body=[
                            Pass(
                                semicolon=MaybeSentinel.DEFAULT,
                            ),
                        ],
                        leading_lines=[],
                        trailing_whitespace=TrailingWhitespace(
                            whitespace=SimpleWhitespace(
                                value='',
                            ),
                            comment=None,
                            newline=Newline(
                                value=None,
                            ),
                        ),
                    ),
                ],
                header=TrailingWhitespace(
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
                indent=None,
                footer=[],
            ),
            decorators=[],
            returns=None,
            asynchronous=None,
            leading_lines=[
                EmptyLine(
                    indent=True,
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
                EmptyLine(
                    indent=True,
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
            ],
            lines_after_decorators=[],
            whitespace_after_def=SimpleWhitespace(
                value=' ',
            ),
            whitespace_after_name=SimpleWhitespace(
                value='',
            ),
            whitespace_before_params=SimpleWhitespace(
                value='',
            ),
            whitespace_before_colon=SimpleWhitespace(
                value='',
            ),
        ),
        FunctionDef(
            name=Name(
                value='_internal_function',
                lpar=[],
                rpar=[],
            ),
            params=Parameters(
                params=[],
                star_arg=MaybeSentinel.DEFAULT,
                kwonly_params=[],
                star_kwarg=None,
                posonly_params=[],
                posonly_ind=MaybeSentinel.DEFAULT,
            ),
            body=IndentedBlock(
                body=[
                    SimpleStatementLine(
                        body=[
                            Pass(
                                semicolon=MaybeSentinel.DEFAULT,
                            ),
                        ],
                        leading_lines=[],
                        trailing_whitespace=TrailingWhitespace(
                            whitespace=SimpleWhitespace(
                                value='',
                            ),
                            comment=None,
                            newline=Newline(
                                value=None,
                            ),
                        ),
                    ),
                ],
                header=TrailingWhitespace(
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
                indent=None,
                footer=[],
            ),
            decorators=[],
            returns=None,
            asynchronous=None,
            leading_lines=[
                EmptyLine(
                    indent=True,
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
                EmptyLine(
                    indent=True,
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
            ],
            lines_after_decorators=[],
            whitespace_after_def=SimpleWhitespace(
                value=' ',
            ),
            whitespace_after_name=SimpleWhitespace(
                value='',
            ),
            whitespace_before_params=SimpleWhitespace(
                value='',
            ),
            whitespace_before_colon=SimpleWhitespace(
                value='',
            ),
        ),
        ClassDef(
            name=Name(
                value='Clazz',
                lpar=[],
                rpar=[],
            ),
            body=IndentedBlock(
                body=[
                    FunctionDef(
                        name=Name(
                            value='func_in_class',
                            lpar=[],
                            rpar=[],
                        ),
                        params=Parameters(
                            params=[
                                Param(
                                    name=Name(
                                        value='self',
                                        lpar=[],
                                        rpar=[],
                                    ),
                                    annotation=None,
                                    equal=MaybeSentinel.DEFAULT,
                                    default=None,
                                    comma=MaybeSentinel.DEFAULT,
                                    star='',
                                    whitespace_after_star=SimpleWhitespace(
                                        value='',
                                    ),
                                    whitespace_after_param=SimpleWhitespace(
                                        value='',
                                    ),
                                ),
                            ],
                            star_arg=MaybeSentinel.DEFAULT,
                            kwonly_params=[],
                            star_kwarg=None,
                            posonly_params=[],
                            posonly_ind=MaybeSentinel.DEFAULT,
                        ),
                        body=IndentedBlock(
                            body=[
                                SimpleStatementLine(
                                    body=[
                                        Pass(
                                            semicolon=MaybeSentinel.DEFAULT,
                                        ),
                                    ],
                                    leading_lines=[],
                                    trailing_whitespace=TrailingWhitespace(
                                        whitespace=SimpleWhitespace(
                                            value='',
                                        ),
                                        comment=None,
                                        newline=Newline(
                                            value=None,
                                        ),
                                    ),
                                ),
                            ],
                            header=TrailingWhitespace(
                                whitespace=SimpleWhitespace(
                                    value='',
                                ),
                                comment=None,
                                newline=Newline(
                                    value=None,
                                ),
                            ),
                            indent=None,
                            footer=[],
                        ),
                        decorators=[],
                        returns=None,
                        asynchronous=None,
                        leading_lines=[],
                        lines_after_decorators=[],
                        whitespace_after_def=SimpleWhitespace(
                            value=' ',
                        ),
                        whitespace_after_name=SimpleWhitespace(
                            value='',
                        ),
                        whitespace_before_params=SimpleWhitespace(
                            value='',
                        ),
                        whitespace_before_colon=SimpleWhitespace(
                            value='',
                        ),
                    ),
                ],
                header=TrailingWhitespace(
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
                indent=None,
                footer=[],
            ),
            bases=[],
            keywords=[],
            decorators=[],
            lpar=MaybeSentinel.DEFAULT,
            rpar=MaybeSentinel.DEFAULT,
            leading_lines=[
                EmptyLine(
                    indent=True,
                    whitespace=SimpleWhitespace(
                        value='',
                    ),
                    comment=None,
                    newline=Newline(
                        value=None,
                    ),
                ),
            ],
            lines_after_decorators=[],
            whitespace_after_class=SimpleWhitespace(
                value=' ',
            ),
            whitespace_after_name=SimpleWhitespace(
                value='',
            ),
            whitespace_before_colon=SimpleWhitespace(
                value='',
            ),
        ),
    ],
    header=[],
    footer=[],
    encoding='utf-8',
    default_indent='    ',
    default_newline='\n',
    has_trailing_newline=True,
)